# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
desc 'Build the Android application.'
lane :build do |options|
	filename = options[:parameter1]
desc "#{filename}"
	yarn(
		command: 'install',
		package_path: '../package.json'
		)
		
	gradle(
		task: 'clean',
		task: 'assemble',
		build_type: 'Release',
		project_dir: './'
		)

	upload_to_google_drive(
 		 drive_keyfile: '/home/ubuntu/google_drive_service_account/poised-space-290101-b057a2e39420.json',
		service_account: true,
  		folder_id: '1Z79LpNL3tg4tk3Wpdl5NksjqX-susgpS',

	#upload_files: ["/var/lib/jenkins/workspace/tbg_activeclub_reactnative_android_dev/android/app/build/outputs/apk/release/tbg_activeclub_reactnative_1.0.#{filename}-release.apk"]
		
	 upload_files: ["/var/lib/jenkins/workspace/rnboilerplate_reactnative/android/app/build/outputs/apk/release/app-release.apk"]
	
)

end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
